export const dummyAptitudeData = [
  {
    question:
      "Two trains running in opposite directions cross a man standing on the platform in 27 seconds and 17 seconds respectively and they cross each other in 23 seconds. The ratio of their speeds is:",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "1 : 3" },
      { option: "3 : 2" },
      { option: "3 : 4" },
      { option: "None of these" },
    ],
    answers: ["3 : 2"], // index of answer
    questionType: "Quantitative",
    answerType: "Radio",
  },
  {
    question:
      "An aeroplane covers a certain distance at a speed of 240 kmph in 5 hours. To cover the same distance in 1 hours, it must travel at a speed of:",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "300 kmph" },
      { option: "360 kmph" },
      { option: "600 kmph" },
      { option: "720 kmph" },
    ],
    answers: ["720 kmph"],
    questionType: "Quantitative",
    answerType: "Radio",
  },
  {
    question:
      "A can do a work in 15 days and B in 20 days. If they work on it together for 4 days, then the fraction of the work that is left is :",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "1/4" },
      { option: "1/10" },
      { option: "7/15" },
      { option: "8/15" },
    ],
    answers: ["8/15"],
    questionType: "Quantitative",
    answerType: "Radio",
  },
  {
    question:
      "Mr. Thomas invested an amount of Rs. 13,900 divided in two different schemes A and B at the simple interest rate of 14% p.a. and 11% p.a. respectively. If the total amount of simple interest earned in 2 years be Rs. 3508, what was the amount invested in Scheme B?",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "Rs. 6400" },
      { option: "Rs. 6500" },
      { option: "Rs. 7200" },
      { option: "Rs. 7500" },
    ],
    answers: ["Rs. 6400"],
    questionType: "Quantitative",
    answerType: "Radio",
  },
  {
    question:
      "The difference between simple and compound interests compounded annually on a certain sum of money for 2 years at 4% per annum is Re. 1. The sum (in Rs.) is:",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "625" },
      { option: "630" },
      { option: "640" },
      { option: "650" },
    ],
    answers: ["625"],
    questionType: "Quantitative",
    answerType: "Radio",
  },
  {
    question: 'Synonyms of "VENT"',
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "Opening" },
      { option: "End" },
      { option: "Stodge" },
      { option: "Past tense of go" },
    ],
    answers: ["Opening"],
    questionType: "Verbal",
    answerType: "Radio",
  },
  {
    question:
      "Fate smiles ...... those who untiringly grapple with stark realities of life.",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "with" },
      { option: "over" },
      { option: "on" },
      { option: "around" },
    ],
    answers: ["on"],
    questionType: "Verbal",
    answerType: "Radio",
  },
  {
    question: "1->I	 2->immediately	3->salary  4->my	5->want",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "15432" },
      { option: "14523" },
      { option: "45231" },
      { option: "None of the above" },
    ],
    answers: ["15432"],
    questionType: "Verbal",
    answerType: "Radio",
  },
  {
    question: "Despite his best efforts to conceal his anger ......",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "he succeeded in camouflaging his emotions" },
      { option: "he failed to give us an impression of his agony" },
      { option: "people came to know that he was annoyed" },
      { option: "we could detect that he was very happy" },
    ],
    answers: ["people came to know that he was annoyed"],
    questionType: "Verbal",
    answerType: "Checkbox",
  },
  {
    question: "The small child does whatever his father was done.",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "has one" },
      { option: "dod" },
      { option: "had done" },
      { option: "does" },
    ],
    answers: ["does"],
    questionType: "Verbal",
    answerType: "Radio",
  },
  {
    question:
      "If A + B means A is the mother of B; A - B means A is the brother B; A % B means A is the father of B and A x B means A is the sister of B, which of the following shows that P is the maternal uncle of Q?",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "Q - N + M x P" },
      { option: "P + S x N - Q" },
      { option: "P - M + N x Q" },
      { option: "Q - S % P" },
    ],
    answers: ["P - M + N x Q"],
    questionType: "Reasoning",
    answerType: "Radio",
  },
  {
    question: "120, 99, 80, 63, 48, ?",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "35" },
      { option: "38" },
      { option: "39" },
      { option: "40" },
    ],
    answers: ["35"],
    questionType: "Reasoning",
    answerType: "Radio",
  },
  {
    question: "The small child does whatever his father was done.",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "has one" },
      { option: "dod" },
      { option: "had done" },
      { option: "does" },
    ],
    answers: ["does"],
    questionType: "Verbal",
    answerType: "Radio",
  },
  {
    question: "",
    questionImageURL:
      "https://www.linkpicture.com/q/Screenshot-2023-09-13-at-5.29.13-PM.png",
    questionImageDesc:
      "Which symbol will be on the face opposite to the face with symbol * ?",
    options: [
      { option: "@" },
      { option: "$" },
      { option: "+" },
      { option: "8" },
    ],
    answers: ["8"],
    questionType: "Reasoning",
    answerType: "Radio",
  },
  {
    question:
      "A, B, C, D and E are sitting on a bench. A is sitting next to B, C is sitting next to D, D is not sitting with E who is on the left end of the bench. C is on the second position from the right. A is to the right of B and E. A and C are sitting together. In which position A is sitting ?",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "Between B and D" },
      { option: "Between B and C" },
      { option: "Between E and D" },
      { option: "Between D and C" },
    ],
    answers: ["Between B and C"],
    questionType: "Reasoning",
    answerType: "Radio",
  },
  {
    question: "Which of the following provides a reuse mechanism?",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "Abstraction" },
      { option: "Inheritance" },
      { option: "Encapsulation" },
      { option: "Dynamic Binding" },
    ],
    answers: ["Inheritance"],
    questionType: "Technical",
    answerType: "Radio",
  },
  {
    question: "What does the given declaration mean? int (*ptr)[10];",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "ptr is array of pointers to 10 integers" },
      { option: "ptr is a pointer to an array of 10 integers" },
      { option: "ptr is an array of 10 integers" },
      { option: "ptr is an pointer to array" },
    ],
    answers: ["ptr is a pointer to an array of 10 integers"],
    questionType: "Technical",
    answerType: "Radio",
  },
  {
    question: "Which will legally declare, construct, and initialize an array?",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: 'int [] myList = {"1", "2", "3"};' },
      { option: "int [] myList = (5, 8, 2);" },
      { option: "int myList [] [] = {4,9,7,0};" },
      { option: "int myList [] = {4, 3, 7};" },
    ],
    answers: ["int myList [] = {4, 3, 7};"],
    questionType: "Technical",
    answerType: "Radio",
  },
  {
    question: "Which SQL statement is used to insert new data in a database?",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "ADD NEW" },
      { option: "ADD RECORD" },
      { option: "INSERT NEW" },
      { option: "INSERT INTO" },
    ],
    answers: ["INSERT INTO"],
    questionType: "Technical",
    answerType: "Radio",
  },
  {
    question: "What are the valid statements for static keyword in Java?",
    questionImageURL: "",
    questionImageDesc: "",
    options: [
      { option: "We can have static block in a class." },
      {
        option:
          "The static block in a class is executed every time an object of class is created.",
      },
      { option: "We can have static method implementations in interface." },
      { option: "We can define static block inside a method." },
    ],
    answers: [
      "We can have static block in a class.",
      "We can have static method implementations in interface.",
    ],
    questionType: "Technical",
    answerType: "Checkbox",
  },
];
